# Generated by Django 4.2.7
# Initial migration for standalone URL shortener (no dependencies)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # No dependencies - this is a standalone app
    ]

    operations = [
        # This migration represents the CURRENT state of the database
        # after manually removing the account_id column
        # We're not creating the tables (they already exist)
        # Just marking them as migrated
    ]